version: '3.7'

services:
  db:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: website
    ports:
      - "5432:5432"
  django:
    container_name: website
    build: .
    volumes:
      - .:/usr/src/website/prediction
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pg_data: