version: '3.7'

services:
  db:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: website
  django:
    container_name: tarr
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python ./website/manage.py makemigrations --noinput &&
             python ./website/manage.py migrate"
             bash -c "python ./website/manage.py runserver"
    volumes:
      - .:/usr/src/taro/prediction
    ports:
      - 8000:5432
    depends_on:
      - db

volumes:
  pg_data: