# Generated by Django 4.2.6 on 2023-12-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Тип жилья')),
            ],
            options={
                'verbose_name': 'Тип жилья',
                'verbose_name_plural': 'Типы жилья',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('telephone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контактные данные')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('payment_hcs', models.BooleanField(default=False)),
                ('deposit', models.PositiveBigIntegerField(default=0)),
                ('total_area', models.FloatField(max_length=1000)),
                ('kitchen_area', models.FloatField(max_length=100)),
                ('living_area', models.FloatField(max_length=100)),
                ('price_per_meter', models.PositiveBigIntegerField()),
                ('ceiling_hight', models.FloatField(max_length=1000)),
                ('the_method_of_sale', models.CharField(max_length=1000)),
                ('floor', models.PositiveSmallIntegerField()),
                ('prepayment', models.PositiveSmallIntegerField()),
                ('the_rental_period', models.CharField(max_length=100)),
                ('living_conditions', models.CharField(max_length=100)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Жилье',
                'verbose_name_plural': 'Жилье',
            },
        ),
    ]
